title: "Random Thoughts"
author: "Aiman"
description: "--"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "aymen.omg@gmail.com"
twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: jirrian/jekyll-theme-image-grid@main
# settings for image grid homepage
grid_settings:
  show_all_images: true #true - displays all images in grid page, false - only show first (file name of image sorted alphabetically) image of post in grid page
  display: square-cropped #square-cropped - images displayed in square grid and cropped, #square-og - images displayed in square grid and with original aspect ratio, masonry - images displayed in original aspect ratio but staggered (please note this will display the images in top to bottom order instead of left to right)

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
